language: node_js
addons:
  apt:
    packages:
      - python3
      - python3-setuptools
      - python3-pip

node_js:
  - 12

install:
    - npm install
    - python3 -m pip install -r docs/requirements.txt
script:
    - npm run build
    - cp -r app/ gh-pages/
    - cp dist/*.min.js gh-pages/
    - touch gh-pages/.nojekyll
    - echo "chemiscope.org" > gh-pages/CNAME
    # Get the example data files from the previous version
    - git clone --depth=1 https://github.com/$TRAVIS_REPO_SLUG --branch gh-pages old-gh-pages
    - cp old-gh-pages/*.json.gz gh-pages/
    - rm -f gh-pages/standalone.in.html
    - rm -f gh-pages/.gitignore
    # Build the docs
    - cd docs && make html && cd -
    - cp -r docs/_build/html/ gh-pages/docs/
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: gh-pages
